language: python
warnings_are_errors: false

env:
  DOCKER_COMPOSE_VERSION: 1.24.1

script:
  - docker-compose --version
  - docker-compose -f docker-compose-dev.yml pull
  - docker-compose -f docker-compose-dev.yml build
