language: python
warnings_are_errors: false
before_install:
- curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
- sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu
  $(lsb_release -cs) stable"
- sudo apt-get update
- sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce
env:
  DOCKER_COMPOSE_VERSION: 1.24.1
  global:
  - secure: gcOZCdlRKE2lr9tFPhO5UNYH8cF3NuzaMg17aPHr0XlchFs72/x2Why2xBvzAiPSLRJX9w6pRjYL9P9Qv5WXJFjreQvY50WVKkhy4/k0fKYItJptjfy8Soj2bw45paMqnz6fyYy+hWgaOvg+4BohDQq7dSE/TOPszItEclPADoeRVHp/SwSc+jQvYoTrgoC0OkmPgWNiLL3qYQlFdR4xFuju3aL5SIqdTSywrFGR/IRHBQmLI1yNHdvIuFEuOk2fsiul8iKXzpeT79j9Czi7spjX+iAOd7ccL+NdUNS7ZNknYponF56lu5mBPCqPELpm+aQb+40KbnAInySGWl6KTCaR8ROb85zoAVboPzv9O5W/Rf/oMRgF30OttTCtZS5feDJmd4eUW57bwEwAT9SCcAhGJUpvrtCeI0PcVD+TTRv4YRLjIlDW/yF/7gpUmNXP09WJ1ZzIdspyofpyVO0nUBOsz/PzO7KVZvLxTMZRg5dPEsVg5FnMeErziisFE97fuWGS7HsIOiVYCU4/VfraJchxdQHHY1B10ntric6Iv9gJ3M767lN4bHyqlxJB1E/D+hkNLSS+MVo1eifuismgB5CnrwjpyVbmYrY/sPVii9xCdQ6c+cXvtNupTvhK6Tpu2Ec+xC/LlJbzK9xQtKWZOrLyZGUxPKqsk1LD4Oh4zEc=
  - secure: oC2TVEnZ174M168uFiBLdwTmx1CzySK4NcTGEh35eVfz9oUJ0h9iKw9/pey/AMjNz0qt0fOjEiEAj0A5OQOspcsNhts/tHnO05J+GvtORznywAnEK/6nEh9292sTmGc1W6H3Dhbkkr0FhIFhVoSA5vX0Ay5jski0jVUDmK89jYOAC3CRLAPXUgiVvkptkFJq8vVZI46FSJMN2Ub5XapbNPnQppVDSzjMWaqREeN3/TIJC/44neyA2mPzV94DR9GjthmLb94XqU4SO6eg9mxlO5/ZDkogR114H0xfXGiK8kQNGduujE7E9tBTSE0czpHe7aKih4KOGeIgmO8QvFzZHUHrzvPpUOwP/YEPpJ5qGTFWImeu97j7fCus0AvrHjqKxzYAzYVZOokjExiMr4niduh0ZBs+RwnP0TnXtlyCSn+zZMtA2WbLLuLy4uDVDJHsa/xDyVNpYR+0x+a6RHXtyUXar+P2jG0w8D7tDhMEEqH3I38Yjsg92qFwB/4keLwR4mFnGFb6nliG0U+bNuPJdx5zyoszS07uKQnXL+WC9saosjAFjZREiSe7yqhQdOunslgkvJ2cAbVB74Qajgg7l7ddOaOYIufWzswE5z6YEV+l1ebU6t1P3dOFrNk68jCQp5e4cfC1lx1My/mgoFfovi/QpIuS5KWgGYM7V6QNceM=
script:
- docker-compose --version
- echo "$DOCKER_PASSWORD" | docker login registry.gitlab.com --username "$DOCKER_USERNAME"
  --password-stdin
- docker build -t registry.gitlab.com/weskerfoot/kettleblog:$(git log -1 --pretty=%h)
  app
- docker push registry.gitlab.com/weskerfoot/kettleblog:$(git log -1 --pretty=%h)
